name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    defaults:
      run:
        working-directory: front-end

    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy to GitHub Pages
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./front-end/dist
